Adds SSH key to agent

diff --git a/install-ssh-key/action.yml b/install-ssh-key/action.yml
--- a/install-ssh-key/action.yml
+++ b/install-ssh-key/action.yml
@@ -9,11 +9,37 @@ inputs:
     description: Name of the file to store the key in.
     required: false
     default: id_rsa
+  op-password-reference:
+    description: Reference to the password for the SSH key in 1Password.
+    required: false
 runs:
   using: composite
   steps:
     - name: Install SSH Key
       run: |
         mkdir -p ~/.ssh
-        op read --out-file ~/.ssh/${{ inputs.filename }} "${{ inputs.op-reference }}"
+        SSH_KEY_PATH="$HOME/.ssh/${{ inputs.filename }}"
+        SSH_KEY_PASSWORD="${{ inputs.op-password-reference }}"
+        op read --out-file $SSH_KEY_PATH "${{ inputs.op-reference }}"
+        if [ -z "$SSH_KEY_PASSWORD" ]; then
+          # Add SSH key without password.
+          ssh-add $SSH_KEY_PATH
+        else
+          # Create script that echoes the password to be used by ssh-add.
+          ASKPASS_SCRIPT=$(mktemp)
+          chmod +x $ASKPASS_SCRIPT
+          echo "#!/bin/bash" > $ASKPASS_SCRIPT
+          echo "echo $SSH_KEY_PASSWORD" >> $ASKPASS_SCRIPT
+          # Add the SSH key using ssh-add. 
+          function timeout() {
+            perl -e 'alarm shift; exec @ARGV' "$@" > /dev/null 2>&1
+          }
+          DISPLAY=1 SSH_ASKPASS=$ASKPASS_SCRIPT timeout 3 ssh-add $SSH_KEY_PATH < /dev/null
+          SSH_ADD_STATUS=$?
+          rm $ASKPASS_SCRIPT
+          if [ $SSH_ADD_STATUS -ne 0 ]; then
+            echo "Failed to add SSH key. Incorrect password or other error."
+            exit 1
+          fi
+        fi
       shell: bash
